version: "3.9"

services:
  sanfrancisco:
    depends_on:
      - rincon
      - jaeger
    image: pacificesports/sanfrancisco
    ports:
      - "${SF_PORT}:${SF_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "SanFrancisco"
      PORT: $SF_PORT
      RINCON_PORT: $RINCON_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $SF_DISCORD_CHANNEL
      STATUS_EMAIL: $SF_STATUS_EMAIL
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT

  rincon:
    depends_on:
      - jaeger
    image: pacificesports/rincon
    ports:
      - "${RINCON_PORT}:${RINCON_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "Rincon"
      PORT: $RINCON_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      EMAIL_ADDRESS: $RINCON_EMAIL_ADDRESS
      EMAIL_PASSWORD: $RINCON_EMAIL_PASSWORD
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $RINCON_DISCORD_CHANNEL
      STATUS_EMAIL: $RINCON_STATUS_EMAIL
      REGISTRY_UPDATE_DELAY: $RINCON_REGISTRY_UPDATE_DELAY

  berkeley:
    depends_on:
      - jaeger
    image: pacificesports/berkeley
    ports:
      - "${BERKELEY_PORT}:${BERKELEY_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "Berkeley"
      PORT: $BERKELEY_PORT
      RINCON_PORT: $RINCON_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $BERKELEY_DISCORD_CHANNEL
      STATUS_EMAIL: $BERKELEY_STATUS_EMAIL
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT