version: "3.9"

services:
  sanfrancisco:
    depends_on:
      - rincon
    image: pacificesports/sanfrancisco
    ports:
      - "${SF_PORT}:${SF_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "SanFrancisco"
      PORT: $SF_PORT
      RINCON_PORT: $RINCON_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $SF_DISCORD_CHANNEL
      STATUS_EMAIL: $SF_STATUS_EMAIL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT

  rincon:
    image: pacificesports/rincon
    ports:
      - "${RINCON_PORT}:${RINCON_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "Rincon"
      PORT: $RINCON_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      EMAIL_ADDRESS: $RINCON_EMAIL_ADDRESS
      EMAIL_PASSWORD: $RINCON_EMAIL_PASSWORD
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $RINCON_DISCORD_CHANNEL
      STATUS_EMAIL: $RINCON_STATUS_EMAIL
      REGISTRY_UPDATE_DELAY: $RINCON_REGISTRY_UPDATE_DELAY

  sacramento:
    depends_on:
      - rincon
    image: pacificesports/sacramento
    ports:
      - "${SACRAMENTO_PORT}:${SACRAMENTO_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "Sacramento"
      PORT: $SACRAMENTO_PORT
      RINCON_PORT: $RINCON_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $SACRAMENTO_DISCORD_CHANNEL
      STATUS_EMAIL: $SACRAMENTO_STATUS_EMAIL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT

  berkeley:
    depends_on:
      - rincon
    image: pacificesports/berkeley
    ports:
      - "${BERKELEY_PORT}:${BERKELEY_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "Berkeley"
      PORT: $BERKELEY_PORT
      RINCON_PORT: $RINCON_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $BERKELEY_DISCORD_CHANNEL
      STATUS_EMAIL: $BERKELEY_STATUS_EMAIL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT

  sanjose:
    depends_on:
      - rincon
    image: pacificesports/sanjose
    ports:
      - "${SANJOSE_PORT}:${SANJOSE_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "SanJose"
      PORT: $SANJOSE_PORT
      RINCON_PORT: $RINCON_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $SANJOSE_DISCORD_CHANNEL
      STATUS_EMAIL: $SANJOSE_STATUS_EMAIL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT

  monterey:
    depends_on:
      - rincon
    image: pacificesports/monterey
    ports:
      - "${MONTEREY_PORT}:${MONTEREY_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "Monterey"
      PORT: $MONTEREY_PORT
      RINCON_PORT: $RINCON_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $MONTEREY_DISCORD_CHANNEL
      STATUS_EMAIL: $MONTEREY_STATUS_EMAIL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT

  losangeles:
    depends_on:
      - rincon
    image: pacificesports/losangeles
    ports:
      - "${LOSANGELES_PORT}:${LOSANGELES_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "LosAngeles"
      PORT: $LOSANGELES_PORT
      RINCON_PORT: $RINCON_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $LOSANGELES_DISCORD_CHANNEL
      STATUS_EMAIL: $LOSANGELES_STATUS_EMAIL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT