name: Azure Staging Deployment
run-name: Triggered by ${{ github.event_name }} to ${{ github.ref }} by @${{ github.actor }}

env:
  FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
  ENV_STAGE: ${{ secrets.ENV_STAGE }}

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Copy files
        run: |
          touch .env
          echo "${{ secrets.ENV_STAGE }}" > .env
          touch lib/firebase_options.dart
          echo "${{ secrets.FIREBASE_OPTIONS }}" > lib/firebase_options.dart
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get Dependencies
        run: flutter pub get
      - name: Build
        run: flutter build web --release
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_MEADOW_0BFCD0D1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "build/web" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build/web" # Built app content directory - optional
          production_branch: "main"
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_MEADOW_0BFCD0D1E }}
          action: "close"
